name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install and test in the client directory
      - name: Install dependencies and run tests in client
        working-directory: my-app/client
        run: |
          npm ci
          npm run build --if-present
          npm test

      # Install and test in the server directory
      - name: Install dependencies and run tests in server
        working-directory: my-app/server
        run: |
          npm ci
          npm run build --if-present
          npm test
